name: Build Hikari-LLVM19 on Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake ninja-build python3

    - name: Configure CMake
      run: |
        cmake -S llvm -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DLLVM_ENABLE_PROJECTS="clang;lld" \
          -DLLVM_TARGETS_TO_BUILD="X86;ARM;AArch64" \
          -DLLVM_ENABLE_ZSTD=OFF \
          -DLLVM_INCLUDE_TESTS=OFF \
          -DLLVM_INCLUDE_EXAMPLES=OFF \
          -DLLVM_INCLUDE_UTILS=OFF \
          -DLLVM_INCLUDE_BENCHMARKS=OFF \
          -DLLVM_BUILD_TOOLS=OFF \
          -DLLVM_INSTALL_TOOLCHAIN_ONLY=ON \
          -DCMAKE_INSTALL_PREFIX="install"

    - name: Build the project
      run: cmake --build build

    - name: Package the build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Hikari-LLVM-linux
        path: install/
